title: "Yachana Arora"
description: "SDE @ Amazon | Former SDE Intern ’25 @ Amazon | Former SWE Intern ’24 @ Microsoft | B.Tech @ NIT Hamirpur"
url: ""                 # set after first deploy, e.g., https://<user>.github.io/portfolio-jtd
baseurl: ""             # keep empty for user/organization pages
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
color_scheme: nil       # light by default; supports 'dark'
markdown: kramdown

# Just the Docs options
just_the_docs:
  logo: false
  search_enabled: true
  back_to_top: true
  back_to_top_text: "Back to top"
  show_navbar: true
  nav_sort: case_insensitive

# Useful external links in the top-right
aux_links:
  "LinkedIn":
    - "https://www.linkedin.com/in/yachanaarora04/"
  "Email":
    - "mailto:someone@example.com"
  "GitHub":
    - "https://github.com/your-handle"

# Build
plugins:
  - jekyll-remote-theme

# Collections not needed; simple pages are fine
