title: "Yachana Arora"
description: "SDE @ Amazon | Former SDE Intern ’25 @ Amazon | Former SWE Intern ’24 @ Microsoft | B.Tech @ NIT Hamirpur"
url: "https://yachanaarora04.github.io"
baseurl: ""
remote_theme: just-the-docs/just-the-docs
color_scheme: nil
markdown: kramdown

# Just the Docs options
just_the_docs:
  logo: false
  search_enabled: true
  back_to_top: true
  back_to_top_text: "Back to top"
  show_navbar: true
  nav_sort: case_insensitive
  includes_css:
    - assets/css/custom.css

# Useful external links in the top-right
aux_links:
  "LinkedIn":
    - "https://www.linkedin.com/in/yachanaarora04/"
  "Email":
    - "mailto:someone@example.com"
  "GitHub":
    - "https://github.com/yachanaarora04"

# Build
plugins:
  - jekyll-remote-theme

# Apply default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# Blog settings
permalink: /blog/:title/
